// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SyndiceoWeb.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Syndiceo.Data.Models;

public partial class Apartment
{
    public int ApartmentId { get; set; }

    public int EntranceId { get; set; }

    public int ApartmentNumber { get; set; }

    public string Note { get; set; }

    public bool IsMarked { get; set; }

    public int? OwnerId { get; set; }

    public int? ResidentCount { get; set; }

    public virtual ICollection<ApartmentTransaction> ApartmentTransactions { get; set; } = new List<ApartmentTransaction>();

    public virtual ICollection<Debt> Debts { get; set; } = new List<Debt>();

    public virtual Entrance Entrance { get; set; }

    public virtual Owner Owner { get; set; }

    public virtual ICollection<Owner> Owners { get; set; } = new List<Owner>();
    public string UserId { get; set; } 
    public bool IsConfirmed { get; set; } = false; 

    [ForeignKey("UserId")]
    public virtual SyndiceoWebUser User { get; set; }
}