// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Data.Models;

public partial class Debt
{
    public int Id { get; set; }

    public int? ApartmentId { get; set; }

    public decimal TotalSum { get; set; }

    public decimal PaidSum { get; set; }

    public decimal? RemainingSum { get; set; }

    public virtual Apartment Apartment { get; set; }
}