// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Data.Models;

public partial class Document
{
    public int DocumentId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public DateTime UploadDate { get; set; }

    public int EntranceId { get; set; }

    public virtual Entrance Entrance { get; set; }
}