// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Data.Models;

public partial class EntranceTransaction
{
    public int Id { get; set; }

    public int EntranceId { get; set; }

    public int CategoryId { get; set; }

    public decimal Amount { get; set; }

    public DateOnly TransDate { get; set; }

    public string Description { get; set; }

    public int? ApartmentId { get; set; }

    public virtual Category Category { get; set; }

    public virtual Entrance Entrance { get; set; }
}