// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Data.Models;

public partial class Login
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string PersonName { get; set; }
    public string SecurityQuestion { get; set; }
    public string SecurityAnswerHash { get; set; }

    public string Email { get; set; }

    public bool RememberMe { get; set; }
}