// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Data.Models;

public partial class Maintenance
{
    public int MaintenanceId { get; set; }

    public int EntranceId { get; set; }

    public string Description { get; set; }

    public int? Price { get; set; }

    public DateTime DateOfMaintenance { get; set; }

    public virtual Entrance Entrance { get; set; }
}