// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Data.Models;

public partial class Owner
{
    public int OwnerId { get; set; }

    public string OwnerName { get; set; }

    public string PhoneNumber { get; set; }

    public int ApartmentId { get; set; }

    public virtual Apartment Apartment { get; set; }

    public virtual ICollection<Apartment> Apartments { get; set; } = new List<Apartment>();
}