// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Syndiceo.Data.Models;

#nullable disable

namespace SyndiceoWeb.Data.Migrations
{
    [DbContext(typeof(SyndiceoDBContext))]
    partial class SyndiceoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Syndiceo.Data.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AddressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId")
                        .HasName("PK__Addresse__091C2A1B23DF249D");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("EntranceId")
                        .HasColumnType("int")
                        .HasColumnName("EntranceID");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("ResidentCount")
                        .HasColumnType("int");

                    b.HasKey("ApartmentId")
                        .HasName("PK__Apartmen__CBDF5744AB8A6A79");

                    b.HasIndex("EntranceId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.ApartmentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("TransDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Apartmen__3214EC070352F544");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ApartmentTransactions");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlockID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("AddressID");

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BlockId")
                        .HasName("PK__Blocks__1442151126C24296");

                    b.HasIndex("AddressId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Cashbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("EntranceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Cashbox__3214EC077283E26E");

                    b.HasIndex("EntranceId");

                    b.ToTable("Cashbox", (string)null);
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Appliance")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kind")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC072BF5793F");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidSum")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("RemainingSum")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TotalSum]-[PaidSum])", true);

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Debts__3214EC0780AC33ED");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("EntranceId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime");

                    b.HasKey("DocumentId")
                        .HasName("PK__Document__1ABEEF0FEFCCF606");

                    b.HasIndex("EntranceId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Entrance", b =>
                {
                    b.Property<int>("EntranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EntranceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntranceId"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int")
                        .HasColumnName("BlockID");

                    b.Property<string>("EntranceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaintenanceHistory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntranceId")
                        .HasName("PK__Entrance__C52C8B3825D0F9DD");

                    b.HasIndex("BlockId");

                    b.ToTable("Entrances");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.EntranceTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EntranceId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TransDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Entrance__3214EC0719957C67");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EntranceId");

                    b.ToTable("EntranceTransactions");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("person_name");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Maintenance", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<DateTime>("DateOfMaintenance")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntranceId")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceId")
                        .HasName("PK__Maintena__E60542D591F22607");

                    b.HasIndex("EntranceId");

                    b.ToTable("Maintenance", (string)null);
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OwnerId")
                        .HasName("PK__Owners__819385B8B15E0D62");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.TotalSum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EntranceId")
                        .HasColumnType("int");

                    b.Property<int>("Summary")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TotalSum__3214EC070AB196E0");

                    b.HasIndex("EntranceId");

                    b.ToTable("TotalSum", (string)null);
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Apartment", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Entrance", "Entrance")
                        .WithMany("Apartments")
                        .HasForeignKey("EntranceId")
                        .IsRequired()
                        .HasConstraintName("FK__Apartment__Entra__412EB0B6");

                    b.HasOne("Syndiceo.Data.Models.Owner", "Owner")
                        .WithMany("Apartments")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK_Apartments_Owners");

                    b.Navigation("Entrance");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.ApartmentTransaction", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Apartment", "Apartment")
                        .WithMany("ApartmentTransactions")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Apartment__Apart__3F115E1A");

                    b.HasOne("Syndiceo.Data.Models.Category", "Category")
                        .WithMany("ApartmentTransactions")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Apartment__Categ__40058253");

                    b.Navigation("Apartment");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Block", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Address", "Address")
                        .WithMany("Blocks")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK__Blocks__AddressI__3B75D760");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Cashbox", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Entrance", "Entrance")
                        .WithMany("Cashboxes")
                        .HasForeignKey("EntranceId")
                        .IsRequired()
                        .HasConstraintName("FK__Cashbox__Entranc__4E53A1AA");

                    b.Navigation("Entrance");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Debt", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Apartment", "Apartment")
                        .WithMany("Debts")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK__Debts__Apartment__0E391C95");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Document", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Entrance", "Entrance")
                        .WithMany("Documents")
                        .HasForeignKey("EntranceId")
                        .IsRequired()
                        .HasConstraintName("FK__Documents__Entra__18EBB532");

                    b.Navigation("Entrance");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Entrance", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Block", "Block")
                        .WithMany("Entrances")
                        .HasForeignKey("BlockId")
                        .IsRequired()
                        .HasConstraintName("FK__Entrances__Block__3E52440B");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.EntranceTransaction", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Category", "Category")
                        .WithMany("EntranceTransactions")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__EntranceT__Categ__47A6A41B");

                    b.HasOne("Syndiceo.Data.Models.Entrance", "Entrance")
                        .WithMany("EntranceTransactions")
                        .HasForeignKey("EntranceId")
                        .IsRequired()
                        .HasConstraintName("FK__EntranceT__Entra__46B27FE2");

                    b.Navigation("Category");

                    b.Navigation("Entrance");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Maintenance", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Entrance", "Entrance")
                        .WithMany("Maintenances")
                        .HasForeignKey("EntranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_Entrance");

                    b.Navigation("Entrance");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Owner", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Apartment", "Apartment")
                        .WithMany("Owners")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Owners__Apartmen__5DCAEF64");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.TotalSum", b =>
                {
                    b.HasOne("Syndiceo.Data.Models.Block", "Entrance")
                        .WithMany("TotalSums")
                        .HasForeignKey("EntranceId")
                        .HasConstraintName("FK__TotalSum__Entran__756D6ECB");

                    b.Navigation("Entrance");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Address", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentTransactions");

                    b.Navigation("Debts");

                    b.Navigation("Owners");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Block", b =>
                {
                    b.Navigation("Entrances");

                    b.Navigation("TotalSums");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Category", b =>
                {
                    b.Navigation("ApartmentTransactions");

                    b.Navigation("EntranceTransactions");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Entrance", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Cashboxes");

                    b.Navigation("Documents");

                    b.Navigation("EntranceTransactions");

                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("Syndiceo.Data.Models.Owner", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
