// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyndiceoWeb.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public string Street { get; set; }

    public virtual ICollection<Block> Blocks { get; set; } = new List<Block>();
}