// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyndiceoWeb.Models;

public partial class Cashbox
{
    public int Id { get; set; }

    public decimal CurrentBalance { get; set; }

    public int EntranceId { get; set; }

    public virtual Entrance Entrance { get; set; }
}