// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyndiceoWeb.Models;

public partial class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Kind { get; set; }

    public string Appliance { get; set; }

    public virtual ICollection<ApartmentTransaction> ApartmentTransactions { get; set; } = new List<ApartmentTransaction>();

    public virtual ICollection<EntranceTransaction> EntranceTransactions { get; set; } = new List<EntranceTransaction>();
}