// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyndiceoWeb.Models;

public partial class Entrance
{
    public int EntranceId { get; set; }

    public int BlockId { get; set; }

    public string EntranceName { get; set; }

    public string MaintenanceHistory { get; set; }

    public virtual ICollection<Apartment> Apartments { get; set; } = new List<Apartment>();

    public virtual Block Block { get; set; }

    public virtual ICollection<Cashbox> Cashboxes { get; set; } = new List<Cashbox>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<EntranceTransaction> EntranceTransactions { get; set; } = new List<EntranceTransaction>();

    public virtual ICollection<Maintenance> Maintenances { get; set; } = new List<Maintenance>();
}