// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Models;

public partial class Block
{
    public int BlockId { get; set; }

    public int AddressId { get; set; }

    public string BlockName { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<Entrance> Entrances { get; set; } = new List<Entrance>();

    public virtual ICollection<TotalSum> TotalSums { get; set; } = new List<TotalSum>();
}