// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Syndiceo.Models;

public partial class TotalSum
{
    public int Id { get; set; }

    public int? EntranceId { get; set; }

    public int Summary { get; set; }

    public virtual Block Entrance { get; set; }
}