// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using SyndiceoWeb.Areas.Identity.Data;
using SyndiceoWeb.Models;
using System;
using System.Collections.Generic;

namespace SyndiceoWeb.Data;

public partial class SyndiceoDBContext : IdentityDbContext<SyndiceoWebUser>
{
    public SyndiceoDBContext()
    {
    }

    public SyndiceoDBContext(DbContextOptions<SyndiceoDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Apartment> Apartments { get; set; }

    public virtual DbSet<ApartmentTransaction> ApartmentTransactions { get; set; }

    public virtual DbSet<Block> Blocks { get; set; }

    public virtual DbSet<Cashbox> Cashboxes { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Debt> Debts { get; set; }

    public virtual DbSet<Document> Documents { get; set; }

    public virtual DbSet<Entrance> Entrances { get; set; }

    public virtual DbSet<EntranceTransaction> EntranceTransactions { get; set; }

    public virtual DbSet<Login> Logins { get; set; }

    public virtual DbSet<Maintenance> Maintenances { get; set; }

    public virtual DbSet<Owner> Owners { get; set; }

    public virtual DbSet<TotalSum> TotalSums { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=SyndiceoDB;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("PK__Addresse__091C2A1B23DF249D");

            entity.Property(e => e.AddressId).HasColumnName("AddressID");
            entity.Property(e => e.Street)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Apartment>(entity =>
        {
            entity.HasKey(e => e.ApartmentId).HasName("PK__Apartmen__CBDF5744AB8A6A79");

            entity.Property(e => e.ApartmentId).HasColumnName("ApartmentID");
            entity.Property(e => e.EntranceId).HasColumnName("EntranceID");

            entity.HasOne(d => d.Entrance).WithMany(p => p.Apartments)
                .HasForeignKey(d => d.EntranceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Apartment__Entra__412EB0B6");

            entity.HasOne(d => d.Owner).WithMany(p => p.Apartments)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("FK_Apartments_Owners");
        });

        modelBuilder.Entity<ApartmentTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Apartmen__3214EC070352F544");

            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Description).HasMaxLength(255);

            entity.HasOne(d => d.Apartment).WithMany(p => p.ApartmentTransactions)
                .HasForeignKey(d => d.ApartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Apartment__Apart__3F115E1A");

            entity.HasOne(d => d.Category).WithMany(p => p.ApartmentTransactions)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Apartment__Categ__40058253");
        });

        modelBuilder.Entity<Block>(entity =>
        {
            entity.HasKey(e => e.BlockId).HasName("PK__Blocks__1442151126C24296");

            entity.Property(e => e.BlockId).HasColumnName("BlockID");
            entity.Property(e => e.AddressId).HasColumnName("AddressID");
            entity.Property(e => e.BlockName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Address).WithMany(p => p.Blocks)
                .HasForeignKey(d => d.AddressId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Blocks__AddressI__3B75D760");
        });

        modelBuilder.Entity<Cashbox>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Cashbox__3214EC077283E26E");

            entity.ToTable("Cashbox");

            entity.Property(e => e.CurrentBalance).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Entrance).WithMany(p => p.Cashboxes)
                .HasForeignKey(d => d.EntranceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cashbox__Entranc__4E53A1AA");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC072BF5793F");

            entity.Property(e => e.Appliance).HasMaxLength(20);
            entity.Property(e => e.Kind).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Debt>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Debts__3214EC0780AC33ED");

            entity.Property(e => e.PaidSum).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.RemainingSum)
                .HasComputedColumnSql("([TotalSum]-[PaidSum])", true)
                .HasColumnType("decimal(11, 2)");
            entity.Property(e => e.TotalSum).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Apartment).WithMany(p => p.Debts)
                .HasForeignKey(d => d.ApartmentId)
                .HasConstraintName("FK__Debts__Apartment__0E391C95");
        });

        modelBuilder.Entity<Document>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("PK__Document__1ABEEF0FEFCCF606");

            entity.Property(e => e.FileName).IsRequired();
            entity.Property(e => e.FilePath).IsRequired();
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.HasOne(d => d.Entrance).WithMany(p => p.Documents)
                .HasForeignKey(d => d.EntranceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Documents__Entra__18EBB532");
        });

        modelBuilder.Entity<Entrance>(entity =>
        {
            entity.HasKey(e => e.EntranceId).HasName("PK__Entrance__C52C8B3825D0F9DD");

            entity.Property(e => e.EntranceId).HasColumnName("EntranceID");
            entity.Property(e => e.BlockId).HasColumnName("BlockID");
            entity.Property(e => e.EntranceName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Block).WithMany(p => p.Entrances)
                .HasForeignKey(d => d.BlockId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entrances__Block__3E52440B");
        });

        modelBuilder.Entity<EntranceTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Entrance__3214EC0719957C67");

            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Description).HasMaxLength(255);

            entity.HasOne(d => d.Category).WithMany(p => p.EntranceTransactions)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EntranceT__Categ__47A6A41B");

            entity.HasOne(d => d.Entrance).WithMany(p => p.EntranceTransactions)
                .HasForeignKey(d => d.EntranceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EntranceT__Entra__46B27FE2");
        });

        modelBuilder.Entity<Login>(entity =>
        {
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("password");
            entity.Property(e => e.PersonName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("person_name");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("username");
        });

        modelBuilder.Entity<Maintenance>(entity =>
        {
            entity.HasKey(e => e.MaintenanceId).HasName("PK__Maintena__E60542D591F22607");

            entity.ToTable("Maintenance");

            entity.Property(e => e.DateOfMaintenance).HasColumnType("datetime");
            entity.Property(e => e.Description).IsRequired();

            entity.HasOne(d => d.Entrance).WithMany(p => p.Maintenances)
                .HasForeignKey(d => d.EntranceId)
                .HasConstraintName("FK_Maintenance_Entrance");
        });

        modelBuilder.Entity<Owner>(entity =>
        {
            entity.HasKey(e => e.OwnerId).HasName("PK__Owners__819385B8B15E0D62");

            entity.Property(e => e.OwnerName).HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(50);

            entity.HasOne(d => d.Apartment).WithMany(p => p.Owners)
                .HasForeignKey(d => d.ApartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Owners__Apartmen__5DCAEF64");
        });

        modelBuilder.Entity<TotalSum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TotalSum__3214EC070AB196E0");

            entity.ToTable("TotalSum");

            entity.HasOne(d => d.Entrance).WithMany(p => p.TotalSums)
                .HasForeignKey(d => d.EntranceId)
                .HasConstraintName("FK__TotalSum__Entran__756D6ECB");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}